# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.28-dev.20251111191145
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cma_model_params import CMAModelParams

class TestCMAModelParams(unittest.TestCase):
    """CMAModelParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CMAModelParams:
        """Test CMAModelParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CMAModelParams`
        """
        model = CMAModelParams()
        if include_optional:
            return CMAModelParams(
                n = 56,
                d = 1.337,
                taup = 1.337,
                taug = 1.337,
                b = 1.337,
                cm = 1.337,
                toff = 1.337,
                t_m = 1.337,
                seed = None,
                eps = 1.337
            )
        else:
            return CMAModelParams(
        )
        """

    def testCMAModelParams(self):
        """Test CMAModelParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
