# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.34-dev.20251114154146
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dexcom_api import DexcomApi


class TestDexcomApi(unittest.TestCase):
    """DexcomApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DexcomApi()

    def tearDown(self) -> None:
        pass

    def test_auth_callback_dexcom_auth_callback_get(self) -> None:
        """Test case for auth_callback_dexcom_auth_callback_get

        Auth Callback
        """
        pass

    def test_get_devices_dexcom_users_self_devices_get(self) -> None:
        """Test case for get_devices_dexcom_users_self_devices_get

        Get Devices
        """
        pass

    def test_get_egvs_dexcom_users_self_egvs_get(self) -> None:
        """Test case for get_egvs_dexcom_users_self_egvs_get

        Get Egvs
        """
        pass

    def test_get_token_dexcom_token_post(self) -> None:
        """Test case for get_token_dexcom_token_post

        Get Token
        """
        pass

    def test_test_dexcom_route_dexcom_test_get(self) -> None:
        """Test case for test_dexcom_route_dexcom_test_get

        Test Dexcom Route
        """
        pass


if __name__ == '__main__':
    unittest.main()
