# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.28-dev.20251111191145
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.t11 import T11

class TestT11(unittest.TestCase):
    """T11 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> T11:
        """Test T11
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `T11`
        """
        model = T11()
        if include_optional:
            return T11(
            )
        else:
            return T11(
        )
        """

    def testT11(self):
        """Test T11"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
