# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.43-dev.20251123003448
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.params_api import ParamsApi


class TestParamsApi(unittest.TestCase):
    """ParamsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ParamsApi()

    def tearDown(self) -> None:
        pass

    def test_default_params_params_default_get(self) -> None:
        """Test case for default_params_params_default_get

        Default Params
        """
        pass

    def test_describe_params_params_describe_post(self) -> None:
        """Test case for describe_params_params_describe_post

        Describe Params
        """
        pass

    def test_params_schema_params_schema_get(self) -> None:
        """Test case for params_schema_params_schema_get

        Params Schema
        """
        pass

    def test_tabulate_params_params_tabulate_post(self) -> None:
        """Test case for tabulate_params_params_tabulate_post

        Tabulate Params
        """
        pass


if __name__ == '__main__':
    unittest.main()
