# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.43-dev.20251123003448
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.body_fit_model_to_data_model_fit_post import BodyFitModelToDataModelFitPost

class TestBodyFitModelToDataModelFitPost(unittest.TestCase):
    """BodyFitModelToDataModelFitPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyFitModelToDataModelFitPost:
        """Test BodyFitModelToDataModelFitPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyFitModelToDataModelFitPost`
        """
        model = BodyFitModelToDataModelFitPost()
        if include_optional:
            return BodyFitModelToDataModelFitPost(
                data = None,
                config = None
            )
        else:
            return BodyFitModelToDataModelFitPost(
                data = None,
        )
        """

    def testBodyFitModelToDataModelFitPost(self):
        """Test BodyFitModelToDataModelFitPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
