# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.34-dev.20251114154146
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.t1 import T1

class TestT1(unittest.TestCase):
    """T1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> T1:
        """Test T1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `T1`
        """
        model = T1()
        if include_optional:
            return T1(
            )
        else:
            return T1(
        )
        """

    def testT1(self):
        """Test T1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
