# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.43-dev.20251123003448
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_fit_model_to_data_model_fit_post(self) -> None:
        """Test case for fit_model_to_data_model_fit_post

        Fit Model To Data
        """
        pass

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        pass

    def test_health_check_run_at_time_health_ws_run_at_time_get(self) -> None:
        """Test case for health_check_run_at_time_health_ws_run_at_time_get

        Health Check Run At Time
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass

    def test_run_at_time_route_model_run_at_time_post(self) -> None:
        """Test case for run_at_time_route_model_run_at_time_post

        Run At Time Route
        """
        pass

    def test_run_at_time_stream_route_model_run_at_time_stream_post(self) -> None:
        """Test case for run_at_time_stream_route_model_run_at_time_stream_post

        Run At Time Stream Route
        """
        pass

    def test_run_model_model_run_post(self) -> None:
        """Test case for run_model_model_run_post

        Run Model
        """
        pass


if __name__ == '__main__':
    unittest.main()
