# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.43-dev.20251123003448
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.data_api import DataApi


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataApi()

    def tearDown(self) -> None:
        pass

    def test_get_sample_dataset_data_sample_download_get(self) -> None:
        """Test case for get_sample_dataset_data_sample_download_get

        Get Sample Dataset
        """
        pass

    def test_stream_sample_dataset_data_sample_stream_get(self) -> None:
        """Test case for stream_sample_dataset_data_sample_stream_get

        Stream Sample Dataset
        """
        pass


if __name__ == '__main__':
    unittest.main()
