# coding: utf-8

# flake8: noqa
"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.43-dev.20251123003448
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.body_fit_model_to_data_model_fit_post import BodyFitModelToDataModelFitPost
from openapi_client.models.cma_model_params import CMAModelParams
from openapi_client.models.config import Config
from openapi_client.models.data import Data
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.params import Params
from openapi_client.models.seed import Seed
from openapi_client.models.t0 import T0
from openapi_client.models.t01 import T01
from openapi_client.models.t1 import T1
from openapi_client.models.t11 import T11
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner

