# coding: utf-8

"""
    PFun CMA Model Backend

    Backend API for the PFun CMA Model, providing endpoints for model parameters, data handling, and model execution.

    The version of the OpenAPI document: 0.4.28-dev.20251111191145
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.seed import Seed
from typing import Optional, Set
from typing_extensions import Self

class CMAModelParams(BaseModel):
    """
    Represents the parameters for a CMA model.  Args:     t (Optional[array_like], optional): Time vector (decimal hours). Defaults to None.     N (int, optional): Number of time points. Defaults to 24.     d (float, optional): Time zone offset (hours). Defaults to 0.0.     taup (float, optional): Circadian-relative photoperiod length. Defaults to 1.0.     taug (float, optional): Glucose response time constant. Defaults to 1.0.     B (float, optional): Glucose Bias constant. Defaults to 0.05.     Cm (float, optional): Cortisol temporal sensitivity coefficient. Defaults to 0.0.     toff (float, optional): Solar noon offset (latitude). Defaults to 0.0.     tM (Tuple[float, float, float], optional): Meal times (hours). Defaults to (7.0, 11.0, 17.5).     seed (Optional[int], optional): Random seed. Set to an integer to enable random noise via parameter 'eps'. Defaults to None.     eps (float, optional): Random noise scale (\"epsilon\"). Defaults to 1e-18.
    """ # noqa: E501
    n: Optional[StrictInt] = Field(default=1024, alias="N")
    d: Optional[Union[StrictFloat, StrictInt]] = 0.0
    taup: Optional[Union[StrictFloat, StrictInt]] = 1.0
    taug: Optional[Union[StrictFloat, StrictInt]] = 1.0
    b: Optional[Union[StrictFloat, StrictInt]] = Field(default=0.05, alias="B")
    cm: Optional[Union[StrictFloat, StrictInt]] = Field(default=0.0, alias="Cm")
    toff: Optional[Union[StrictFloat, StrictInt]] = 0.0
    t_m: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="tM")
    seed: Optional[Seed] = None
    eps: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["N", "d", "taup", "taug", "B", "Cm", "toff", "tM", "seed", "eps"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CMAModelParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of seed
        if self.seed:
            _dict['seed'] = self.seed.to_dict()
        # set to None if t_m (nullable) is None
        # and model_fields_set contains the field
        if self.t_m is None and "t_m" in self.model_fields_set:
            _dict['tM'] = None

        # set to None if seed (nullable) is None
        # and model_fields_set contains the field
        if self.seed is None and "seed" in self.model_fields_set:
            _dict['seed'] = None

        # set to None if eps (nullable) is None
        # and model_fields_set contains the field
        if self.eps is None and "eps" in self.model_fields_set:
            _dict['eps'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CMAModelParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "N": obj.get("N") if obj.get("N") is not None else 1024,
            "d": obj.get("d") if obj.get("d") is not None else 0.0,
            "taup": obj.get("taup") if obj.get("taup") is not None else 1.0,
            "taug": obj.get("taug") if obj.get("taug") is not None else 1.0,
            "B": obj.get("B") if obj.get("B") is not None else 0.05,
            "Cm": obj.get("Cm") if obj.get("Cm") is not None else 0.0,
            "toff": obj.get("toff") if obj.get("toff") is not None else 0.0,
            "tM": obj.get("tM"),
            "seed": Seed.from_dict(obj["seed"]) if obj.get("seed") is not None else None,
            "eps": obj.get("eps")
        })
        return _obj


